server:
  servlet:
    context-path: /

spring:
  application:
    name: LetsJam
  profiles:
    active: dev
  jackson:
    default-property-inclusion: NON_NULL
  messages:
    basename: i18n/common, i18n/letsjam
    encoding: UTF-8
    use-code-as-default-message: true
  
  jpa:
   properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}
        hbm2ddl.auto: create
        #format_sql: true
        #show_sql: true
   open-in-view: false

###############################################
############# LETSJAM PROPERTIES ##############
###############################################