
spring:
  datasource:
    url: jdbc:mysql://database.ccml.it:9002/letsjam?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: letsjam
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb+srv://letsjam:letsjam@letsjam.p9fke.mongodb.net/letsjam?retryWrites=true&w=majority

###############################################
########### LETSJAM PROPERTIES ################
###############################################

